---
apiVersion: v1
kind: Service
metadata:
  name: statefull-postgresql-service
  labels:
    app: statefull-postgresql-service
spec:
  type: ClusterIP
  selector:
    app: statefull-postgresql-statefulset
  ports:
    - port: 5432
      targetPort: 5432