apiVersion: apps/v1
kind: Deployment
metadata:
  name: stateless-fastapi-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        imagePullPolicy: IfNotPresent
        image: my-local-image:latest
        ports:
        - protocol: TCP
          containerPort: 8000